#!/bin/bash
# Written by Draztick

########  Update Section  ##############

echo "[*] Updating repositories..."

{
  apt update 2>/dev/null 
} 2>&1 > /dev/null

if [ $? -eq 0 ]; then
  echo "[+] Repositories updated successfully."
else
  echo "[-] Repositories failed to update."
fi

echo "[*] Updating packages..."

{
  apt upgrade -y 2>/dev/null
} 2>&1 > /dev/null

if [ $? -eq 0 ]; then
  echo "[+] Packages upgrade successfully."
else
  echo "[-] Packages failed to upgrade."
fi

########  In-repo installs  ###############

## Recon and Information Gathering ##

echo "[*] Installing Wireshark..."

{
  apt install -y wireshark 2>/dev/null
} 2>&1 > /dev/null

if [ $? -eq 0 ]; then
  echo "[+] Wireshark installed successfully"
else
  echo "[-] Wireshark failed to install."
fi

## Scanning Tools ##

echo "[*] Installing Nmap..."

{ 
  apt install -y nmap 2>/dev/null
} 2>&1 > /dev/null

if [ $? -eq 0 ]; then
  echo "[+] Nmap installed successfully."
else
  echo "[-] Nmap failed to install."
fi

## 

###### Make required directories #########

if [ -d /opt/ghidra ]; then
  echo "[-] Ghidra directory already exists..."
else
  mkdir /opt/ghidra
  if [ $? -eq 0 ]; then
    echo "[+] Ghidra directory created."
  else
    echo "[-] Ghidra directory creation failed."
  fi
fi

if [ -d /opt/nessus ]; then
  echo "[-] Nessus directory already exists."
else
  mkdir /opt/nessus
  if [ $? -eq 0 ]; then
    echo "[+] Nessus directory created."
  else
    echo "[-] Nessus directory created failed."
  fi
fi

###### Manual Installations ###########


{
  wget http://downloads.metasploit.com/data/releases/metasploit-latest-linux-x64-installer.run
} 2>&1 > /dev/null
chmod +x ./metasploit-latest-linux-x64-installer.run
./metasploit-latest-linux-x64-installer.run

