#!/bin/bash
# Written by Draztick

########  Update Section  ##############

echo "[*] Updating repositories..."

{
  apt update 2>/dev/null 
} 2>&1 > /dev/null

if [ $? -eq 0 ]; then
  echo "[+] Repositories updated successfully."
else
  echo "[-] Repositories failed to update."
fi

echo "[*] Updating packages..."

{
  apt upgrade -y 2>/dev/null
} 2>&1 > /dev/null

if [ $? -eq 0 ]; then
  echo "[+] Packages upgrade successfully."
else
  echo "[-] Packages failed to upgrade."
fi

########  In repo installs  ###############

echo "[*] Installing Nmap..."

{ apt install nmap -y } 2>&1 > /dev/null

if [ $? -eq 0 ]; then
  echo "[+] Nmap installed successfully."
else
  echo "[-] Nmap failed to install."
fi


########  Make necessary directories  #############






####### Manual installs ############





########  Linking  #############
